---

- name: postfix restart
  service: name=postfix state=restarted
  notify: postfix send test mail

- name: "postfix send test mail"
  shell: echo "Test mail from new/updated postfix at" `hostname` | mail -s "Test SMTP `hostname`" {{postfix_send_test_mail_to}}
  when: postfix_send_test_mail_to != ""
